### ISSUE TITLE
license

### ISSUE THREAD

**Issue by superbogy** [editablejs/editable#108]
为什么用 GPL license. 这个开源协议也太不友好了

**Comment by big-camel** [comment]
我觉得还可以呀，你有哪些顾虑？

**Comment by superbogy** [comment]
GPL 有传染性啊，是要使用 gpl 的软件必须要开源。

**Comment by wenerme** [comment]
@big-camel 前端项目一般都不会用 GPL，因为前端项目用 GPL 意味着所有用该库的都必须 GPL，因此不会有前端库 GPL 的。如果有商业计划，建议划分 EE 和 CE 功能，CE MIT 或者 Apache，EE 随意

**Comment by big-camel** [comment]
> @big-camel 前端项目一般都不会用 GPL，因为前端项目用 GPL 意味着所有用该库的都必须 GPL，因此不会有前端库 GPL 的。如果有商业计划，建议划分 EE 和 CE 功能，CE MIT 或者 Apache，EE 随意

谢谢您的建议，我改改
