### ISSUE TITLE
Could not fetch dependencies error

### ISSUE THREAD

**Issue by thsuekfk2** [editablejs/editable#120]
hello. 

https://docs.editablejs.com/learn/plugin-list
An error pops up in Usage.

The error is: error Unable to import dependencies. Try again in a few seconds.

<img width="963" alt="스크린샷 2023-06-07 09 34 09" src="https://github.com/editablejs/editable/assets/76821963/664148be-f640-48ac-9458-5253f5ebc391">

**Comment by big-camel** [comment]
#118
