### ISSUE TITLE
转换成html 后，样式不在了

### ISSUE THREAD

**Issue by lubingxf** [editablejs/editable#126]
**Description**

**Recording**
A GIF or video showing the issue happening. (If you don't include this, there's a very good chance your issue will be closed, because it's much too hard to figure out exactly what is going wrong, and it makes maintenance much harder.)

**Sandbox**
A link to a sandbox where the error can be reproduced.

**Steps**
To reproduce the behavior:

**Expectation**
A clear and concise description of what you expected to happen. (Often it's helpful to test out the behavior of other editors like Google Docs, Medium, Notion, etc. to see how they handle the same issue.)

**Environment**
- Editable Version: [e.g. 0.59]
- Operating System: [e.g. iOS]
- Browser: [e.g. Chrome, Safari]
- TypeScript Version: [e.g. 3.9.7 - required only if it's a TypeScript issue]

**Context**
Add any other context about the problem here. (The fastest way to have an issue fixed is to create a pull request with working, tested code and we'll help merge it. Editable is solving a pretty complex problem, and we can't do it without active contributors, so thank you so much for your help!)

**Comment by big-camel** [comment]
有更详细的描述吗？什么样的样式？什么插件？

**Comment by lubingxf** [comment]
使用插件@editablejs/serializer/html   const html = HTMLSerializer.transformWithEditor(editor)  转html 
![image](https://github.com/editablejs/editable/assets/46311912/8d51e9f0-8032-4ef7-8ffa-715817ebe42e)

**Comment by big-camel** [comment]
有更明确的表述吗？什么样的样式？预期样式什么样的？

**Comment by lubingxf** [comment]
<table  table-layout:fixed;border-collapse:collapse;white-space:nowrap;><colgroup><col  width:297px;></col><col  width:297px;></col><col  width:299px;></col></colgroup><tbody><tr  height:35px;margin:0px;padding:0px;><td colspan="1" rowspan="1"  margin:0px;padding:6px;border:1px solid #d6d6d6;vertical-align:top;display:;><p  >2</p></td><td colspan="1" rowspan="1"  margin:0px;padding:6px;border:1px solid #d6d6d6;vertical-align:top;display:;><p  ></p></td><td colspan="1" rowspan="1"  margin:0px;padding:6px;border:1px solid #d6d6d6;vertical-align:top;display:;><p  ></p></td></tr><tr  height:35px;margin:0px;padding:0px;><td colspan="1" rowspan="1"  margin:0px;padding:6px;border:1px solid #d6d6d6;vertical-align:top;display:;><p  ></p></td><td colspan="1" rowspan="1"  margin:0px;padding:6px;border:1px solid #d6d6d6;vertical-align:top;display:;><p  ></p></td><td colspan="1" rowspan="1"  margin:0px;padding:6px;border:1px solid #d6d6d6;vertical-align:top;display:;><p  ></p></td></tr><tr  height:35px;margin:0px;padding:0px;><td colspan="1" rowspan="1"  margin:0px;padding:6px;border:1px solid #d6d6d6;vertical-align:top;display:;><p  ></p></td><td colspan="1" rowspan="1"  margin:0px;padding:6px;border:1px solid #d6d6d6;vertical-align:top;display:;><p  ></p></td><td colspan="1" rowspan="1"  margin:0px;padding:6px;border:1px solid #d6d6d6;vertical-align:top;display:;><p  ></p></td></tr></tbody></table>
预期样式应该放在  style 里

**Comment by lubingxf** [comment]
预期标签所携带的样式 应该放在style 属性里面

**Comment by big-camel** [comment]
你所说的样式长什么样？
