### ISSUE TITLE
What is self-drawn cursor?And why self-drawn cursor?

### ISSUE THREAD

**Issue by jonsam-ng** [editablejs/editable#3]
我对这个想法很感兴趣，但是我无法查找到 self-drawn cursor 的更多信息，希望作者能够简要介绍下具体的想法和方案。
或许能够在 Readme 中加入这一部分内容能够对大家有更多的帮助。

**Comment by yanmao-cc** [comment]
就是不使用 contenteditable 属性，所有的光标和选区自己绘制以及管理

dom 节点上不使用 [contenteditable](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Global_attributes/contenteditable) 属性
![image](https://user-images.githubusercontent.com/55792257/187622653-5aedd9d8-f152-4f7a-a623-f8a76d6dbf92.png)

这里使用div模拟光标的闪动，以及对选区的绘制。使用 textarea 拦截输入、按键等事件然后做下一步处理
![image](https://user-images.githubusercontent.com/55792257/187623304-3b95c0a2-ac35-427f-be46-abb469de1b11.png)

这样我们只需要设置数据模型的 selection，然后按照selection绘制光标即可，抹平了不同设备与浏览器之间处理selection的差异。也不需要因为节点有了contenteditable属性后，内部节点因为不同设备和浏览器对一些操作造成不同的节点变动后再去修补数据模型

没有了contenteditable，内部可编辑区域和非可编辑区域更容易控制，自由度也更大

**Comment by YaoKaiLun** [comment]
最近在基于 slate 实现移动端的富文本编辑器，遇到了很多使用元素光标和选区会遇到的问题，对于为何使用自绘光标和选区的原因做个补充：
1. iOS 只能对 contenteditable 元素自定义光标和选区的颜色，非 contenteditable 则无效（我们业务希望要保证预览和编辑模式样式一致），android 正常情况下可以，但是 x5 内核不支持，有 bug
2. iOS 的光标和选区在最顶层，所以会出现穿透问题（同时还有光标跟随延迟的问题）
<img width="378" alt="image" src="https://user-images.githubusercontent.com/11460856/218241582-ed1dee70-9eba-489a-bf4c-fc953c5b2781.png">
3.低版本 iOS 对于包含上下标元素的选区渲染有问题
<img width="685" alt="image" src="https://user-images.githubusercontent.com/11460856/218241636-c2a71683-e2b5-40c9-998d-30f38ceee8c4.png">
4. x5 内核对光标和选区的处理，非常糟糕，如下只是一小点（还有长按当前光标位置无反应、长按文本没有默认选中等等问题）
<img width="421" alt="image" src="https://user-images.githubusercontent.com/11460856/218241666-ede896ba-3028-4517-90dd-385b15b91a51.png">

**Comment by YaoKaiLun** [comment]
另外一个比较重要的问题是，我们期望在键盘收起的时候，仍然能够显示光标和选区，这个对于采用元素光标和选区来说，是基本做不到的，最终我们是采用 editablejs 的绘制方案来解决的，在收起键盘的时候，自己在绘制光标和选区

键盘展开的时候
<img width="376" alt="image" src="https://user-images.githubusercontent.com/11460856/218242086-652ef928-6afe-424f-a7ab-af456184532d.png">


键盘收起的时候
<img width="373" alt="image" src="https://user-images.githubusercontent.com/11460856/218242099-84360925-f66e-46ad-aaad-43170027c12f.png">
