### ISSUE TITLE
How to develop

### ISSUE THREAD

**Issue by claviering** [editablejs/editable#48]
README.md
```
# Install
pnpm install

# start up
pnpm dev
```
And openr `http://localhost:3000/playground` 
Failed to compile  because `Module not found: Can't resolve '@editablejs/editor'`

**Comment by big-camel** [comment]
The required environment is: Node.js version greater than or equal to 16.0.0 and pnpm version greater than or equal to 7.0.0. 

Are there any error messages in the Terminal? 

On the first time of executing the pnpm dev command, the packages in the package may not have been built yet. There are no files in the dist folder.

**Comment by claviering** [comment]
node version `v16.13.0`, pnpm version `7.5.1`

the error is

<img width="1408" alt="image" src="https://user-images.githubusercontent.com/16227832/212805802-d3f16aa2-ce5d-4b67-9d69-af2fe14fe7ad.png">

should i build the package in development?
should

**Comment by big-camel** [comment]
You can try executing `pnpm build`

**Comment by big-camel** [comment]
Also, one thing to note, you need to execute it at the root directory of the project, not in the apps/docs directory.

**Comment by claviering** [comment]
yes, at the root directory. I fix it by reinstall `pnpm install`. Because i install it in node version 14 at first.
