### ISSUE TITLE
context menu locale miss

### ISSUE THREAD

**Issue by claviering** [editablejs/editable#54]
<img width="1297" alt="image" src="https://user-images.githubusercontent.com/16227832/215252298-06e1a82d-8eee-4977-b776-8fd7dda8f8de.png">

**Comment by big-camel** [comment]
This issue will be fixed when the multilingual feature is added in the docs (demo site) project. The context-menu plugin can freely expand its title through the items option. To improve decoupling, default items should not be added within the context-menu plugin.
