### ISSUE TITLE
bug:Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by PangYiMing** [editablejs/editable#64]
Select one of the lines of text and enter Chinese, but an error occurs.

<img width="339" alt="image" src="https://user-images.githubusercontent.com/18424614/215464153-32d62c5c-a7c4-4a75-8d11-bad3d2a461a5.png">

error info：
Application error: a client-side exception has occurred (see the browser console for more information).

**Comment by claviering** [comment]
selection from right to left with throw Error
