### ISSUE TITLE
Pressing CMD + LEFT does not move to the start of the row

### ISSUE THREAD

**Issue by Aminadav** [editablejs/editable#85]
On Mac, Press CMD+Left it's like clicking the "HOME" button.
But it does nothing.

Same for CMD+RIGHT.

**Comment by big-camel** [comment]
https://github.com/editablejs/editable/pull/86

**Comment by trueadm** [comment]
CMD+LEFT and CMD+RIGHT should move to the start/end of the line, not the start/end of the block. You can use the `Intl` API to find the beginnings and ends of the line AFAIK.
